#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import rospy
import tf
from std_msgs.msg import Int32
from math import sqrt,atan2,cos,sin,pi
import time
from diff_drive import encoder

PPM = 13610

PPR = 1361

MPM = 1.7

def wheel_encoder_publisher():
    left_wheel_encoder = encoder.Encoder(20, 21)
    right_wheel_encoder = encoder.Encoder(16, 19)
    left_wheel_pub = rospy.Publisher('lwheel_ticks', Int32, queue_size=50)
    right = rospy.Publisher('rwheel_ticks', Int32, queue_size=50)
    rospy.init_node('wheel_encoder_publisher', anonymous=True)
    rospy.loginfo("waiting for Encoders...")
    while not rospy.is_shutdown():
    # Pausing for `tsample` to give CPU time to process encoder signal
        time.sleep(0.002)
        tcurr = time.perf_counter() - tstart
        self.left_wheel_pub(Int32(self.left_wheel_encoder.steps))
        self.right_wheel_pub(Int32(self.left_wheel_encoder.steps))

if __name__ == '__main__':
    try:
        wheel_encoder_publisher()
    except rospy.ROSInterruptException:
        pass
